parts:
  golang-static-http:
    plugin: go1.4-project
    source: git://github.com/mikix/golang-static-http
  webfd:
    plugin: ubuntu
    packages: [python-dev, python-opencv, python-numpy]
  logic.xml:
    plugin: copy
    files:
      logic.xml: bin/logic.xml
      face_detect.py: bin/face_detect.py
  glue:
    plugin: copy
    files:
      wfd: bin/wfd
snappy-metadata: meta
