#!/bin/sh
set -e

cd "$SNAPP_APP_DATA_PATH"

golang-static-http &

export LD_LIBRARY_PATH=$SNAP_APP_PATH/usr/lib/x86_64-linux-gnu/mesa:$SNAP_APP_PATH/usr/lib/lapack:$SNAP_APP_PATH/usr/lib/libblas:$LD_LIBRARY_PATH

while :; do
    python2 $SNAP_APP_PATH/bin/face_detect.py $SNAP_APP_PATH/bin/logic.xml
    sleep 3
done
